spring:
  datasource:
    url: jdbc:mysql://42.192.6.2:34235/kgms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Sicdp2021fkfd@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    # 是否启用flyway
    enabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
    # redis配置
  redis:
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        # 最大连接数量
        max-active: 20
    # 超时
    connect-timeout: 1000
mybatis:
  mapper-locations: classpath:project/mapper/*.xml
server:
  port: 8081
#  pagehelper配置
pagehelper:
  helper-dialect:: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql