spring:
  datasource:
    #url: jdbc:mysql://42.192.6.2:34235/kgms_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #测试数据库
    url: jdbc:mysql://42.192.6.2:34235/kgms_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Sicdp2021fkfd@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        # 最大连接数量
        max-active: 20
    # 超时
    connect-timeout: 1000
    mvc:
      hiddenmethod:
        filter:
          enabled: true
    #neo4j
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
    mongodb:
      host: 42.192.6.2
      port: 34236
      database: kgms

mybatis:
  mapper-locations: classpath:project/mapper/*.xml
server:
  port: 12345
#  pagehelper配置
pagehelper:
  helper-dialect:: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql